/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.PraktikumPemrogramanII;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
